// scripts/seed-products.ts
import { ProductSyncManager } from '../lib/multi-retailer-sync';

// Sample product data for immediate testing
const sampleProducts = [
  {
    id: 'sample_1',
    name: 'Elegant Midi Dress',
    brand: 'StyleCo',
    price: 89.99,
    currency: 'USD',
    images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400'],
    category: 'dresses',
    styleDNA: ['classic-elegant', 'romantic-feminine'],
    sizeOptions: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Burgundy'],
    description: 'A timeless midi dress perfect for any occasion. Features a flattering silhouette and premium fabric.',
    rating: 4.5,
    reviewCount: 127,
    affiliateUrl: 'https://example.com/product/1',
    retailer: 'StyleCo',
    inStock: true,
    tags: ['elegant', 'midi', 'versatile', 'work-appropriate'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'sample_2',
    name: 'Modern Blazer',
    brand: 'ChicWear',
    price: 129.99,
    currency: 'USD',
    images: ['https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400'],
    category: 'outerwear',
    styleDNA: ['modern-chic', 'minimalist-clean'],
    sizeOptions: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'White', 'Camel'],
    description: 'A contemporary blazer that elevates any outfit. Perfect for professional settings or casual chic looks.',
    rating: 4.7,
    reviewCount: 89,
    affiliateUrl: 'https://example.com/product/2',
    retailer: 'ChicWear',
    inStock: true,
    tags: ['blazer', 'professional', 'versatile', 'modern'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'sample_3',
    name: 'Bohemian Maxi Skirt',
    brand: 'FreeSpirit',
    price: 65.99,
    currency: 'USD',
    images: ['https://images.unsplash.com/photo-1583496661160-fb5886a13d24?w=400'],
    category: 'bottoms',
    styleDNA: ['bohemian-free'],
    sizeOptions: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Floral Print', 'Paisley', 'Solid Rust'],
    description: 'A flowing maxi skirt with beautiful prints. Perfect for festivals, beach days, or casual outings.',
    rating: 4.3,
    reviewCount: 156,
    affiliateUrl: 'https://example.com/product/3',
    retailer: 'FreeSpirit',
    inStock: true,
    tags: ['boho', 'maxi', 'flowy', 'festival'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'sample_4',
    name: 'Edgy Leather Jacket',
    brand: 'RockStyle',
    price: 199.99,
    currency: 'USD',
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400'],
    category: 'outerwear',
    styleDNA: ['edgy-bold'],
    sizeOptions: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Brown'],
    description: 'A statement leather jacket that adds edge to any outfit. Premium leather construction with modern details.',
    rating: 4.8,
    reviewCount: 203,
    affiliateUrl: 'https://example.com/product/4',
    retailer: 'RockStyle',
    inStock: true,
    tags: ['leather', 'edgy', 'statement', 'jacket'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'sample_5',
    name: 'Minimalist White Tee',
    brand: 'Essential',
    price: 29.99,
    currency: 'USD',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400'],
    category: 'tops',
    styleDNA: ['minimalist-clean'],
    sizeOptions: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Black', 'Gray'],
    description: 'The perfect basic tee. Premium cotton construction with a flattering fit that works with everything.',
    rating: 4.6,
    reviewCount: 342,
    affiliateUrl: 'https://example.com/product/5',
    retailer: 'Essential',
    inStock: true,
    tags: ['basic', 'essential', 'cotton', 'versatile'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'sample_6',
    name: 'Romantic Lace Blouse',
    brand: 'Feminine',
    price: 79.99,
    currency: 'USD',
    images: ['https://images.unsplash.com/photo-1564257577-4b0b5b1b6c3d?w=400'],
    category: 'tops',
    styleDNA: ['romantic-feminine'],
    sizeOptions: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Ivory', 'Blush', 'Black'],
    description: 'Delicate lace blouse with romantic details. Perfect for date nights or special occasions.',
    rating: 4.4,
    reviewCount: 98,
    affiliateUrl: 'https://example.com/product/6',
    retailer: 'Feminine',
    inStock: true,
    tags: ['lace', 'romantic', 'delicate', 'special-occasion'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'sample_7',
    name: 'Classic Ankle Boots',
    brand: 'StepStyle',
    price: 149.99,
    currency: 'USD',
    images: ['https://images.unsplash.com/photo-1544966503-7cc5ac882d5f?w=400'],
    category: 'shoes',
    styleDNA: ['classic-elegant', 'modern-chic'],
    sizeOptions: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10'],
    colors: ['Black', 'Brown', 'Tan'],
    description: 'Versatile ankle boots that complement any outfit. Quality leather construction with comfortable heel.',
    rating: 4.7,
    reviewCount: 267,
    affiliateUrl: 'https://example.com/product/7',
    retailer: 'StepStyle',
    inStock: true,
    tags: ['boots', 'ankle', 'versatile', 'leather'],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'sample_8',
    name: 'Statement Earrings',
    brand: 'Sparkle',
    price: 39.99,
    currency: 'USD',
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400'],
    category: 'accessories',
    styleDNA: ['edgy-bold', 'romantic-feminine'],
    sizeOptions: ['One Size'],
    colors: ['Gold', 'Silver', 'Rose Gold'],
    description: 'Eye-catching statement earrings that add glamour to any look. Hypoallergenic materials.',
    rating: 4.5,
    reviewCount: 145,
    affiliateUrl: 'https://example.com/product/8',
    retailer: 'Sparkle',
    inStock: true,
    tags: ['earrings', 'statement', 'glamour', 'accessories'],
    lastUpdated: new Date().toISOString(),
  }
];

async function seedProducts() {
  console.log('🌱 Seeding sample products...');
  
  const syncManager = new ProductSyncManager();
  await syncManager.saveToFirebase(sampleProducts);
  
  console.log('✅ Sample products seeded successfully!');
  console.log(`📦 Added ${sampleProducts.length} products across multiple categories`);
  console.log('🎯 Categories: dresses, outerwear, bottoms, tops, shoes, accessories');
  console.log('🎨 Style DNA coverage: All 6 style personalities included');
}

// Run the seeding
seedProducts().catch(console.error);